[package]
name = "ontime"
version = "0.3.1"
edition = "2021"
authors = ["Michael Hall <michael@mbh.sh>"]
description = "Extract subsets of ONT (Nanopore) reads based on time"
repository = "https://github.com/mbhall88/ontime"
homepage = "https://github.com/mbhall88/ontime"
readme = "README.md"
license-file = "LICENSE"
rust-version = "1.65.0"
keywords = ["bioinformatics", "nanopore", "time", "fastq"]
categories = ["science", "command-line-utilities"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
maintenance = { status = "actively-developed" }

[dependencies]
needletail = { version = "0.7.2", features = ["compression"] }
clap = { version = "4.6.0", features = ["derive"] }
niffler = "3.0.0"
thiserror = "2.0.18"
anyhow = "1.0.68"
log = "0.4.17"
env_logger = "0.11.10"
time = { version = "0.3.36", features = ["parsing", "macros", "formatting"] }
lazy_static = "1.4.0"
regex = "1.7.1"
bstr = "1.1.0"
duration-str = "0.21.0"
itertools = "0.14.0"
noodles-bam = "0.88.0"
noodles-bgzf = "0.46.0"
noodles-util = { version = "0.78.0", features = ["alignment"] }
noodles-sam = "0.84.0"

[dev-dependencies]
tempfile = "3.3.0"
assert_cmd = "2.0.8"
indoc = "2.0.7"
